name: Sync and Remove Duplicate School Entries

on:
  push:
    paths:
      - "json/fullSchoolList.json"
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-school-lists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Remove Duplicates, Sort, and Update Lists
        run: |
          node -e '
          const fs = require("fs");

          // File paths
          const fullListPath = "json/fullSchoolList.json";
          const schoolListJsonPath = "json/schoolList.json";
          const schoolListTxtPath = "text/schoolList.txt";
          const schoolListCsvPath = "text/schoolList.csv";

          // Ensure directories exist
          fs.mkdirSync("json", { recursive: true });
          fs.mkdirSync("text", { recursive: true });

          // Load full school list
          let data = JSON.parse(fs.readFileSync(fullListPath, "utf8"));

          // Remove duplicates and sort
          let seen = new Set();
          let cleanedData = data.filter(entry => {
            let name = entry.name?.trim().toLowerCase();
            if (!name || seen.has(name)) return false;
            seen.add(name);
            return true;
          }).sort((a, b) => a.name.localeCompare(b.name));

          // Extract and sort names
          let schoolNames = cleanedData.map(entry => entry.name).sort();

          // Save updated files
          fs.writeFileSync(fullListPath, JSON.stringify(cleanedData, null, 2));
          fs.writeFileSync(schoolListJsonPath, JSON.stringify(schoolNames, null, 2));
          fs.writeFileSync(schoolListTxtPath, schoolNames.join("\n") + "\n");

          // Write CSV file
          const csvContent = "name\n" + schoolNames.map(n => `"${n.replace(/"/g, '""')}"`).join("\n") + "\n";
          fs.writeFileSync(schoolListCsvPath, csvContent);

          console.log("✅ Process completed: Duplicates removed, lists sorted, and files updated.");
          '

      - name: Commit and Push Changes
        run: |
          git config --global user.name "NanduWasTaken BOT"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Check for changes and commit if needed
          git diff --quiet && exit 0  # Exit if no changes
          git add json/fullSchoolList.json json/schoolList.json text/schoolList.txt text/schoolList.csv
          git commit -m "🥂[BOT] Synced & Sorted🥂"
          git push
